sylius_twig_hooks:
  hooks:
    'sylius_shop.account.lyra.saved_cards.index.content.main':
      section:
        template: '@LyranetworkLyraPlugin/shop/account/saved_cards/section.html.twig'
        priority: 150